DOCPATH_ROOT=${DOCPATH_ROOT:=/var/www/html}
DOCPATH_HTTP=${DOCPATH_HTTP:=/var/www/html}
DOCPATH_STATIC=${DOCPATH_STATIC:=/var/www/html}

LOCATION_STATIC=${LOCATION_STATIC:=/content}
LOCATION_VSCODE=${LOCATION_VSCODE:=/vscode}

ENABLE_HTTP=${ENABLE_HTTP:=true}
ENABLE_STATIC=${ENABLE_STATIC:=true}
ENABLE_VSCODE=${ENABLE_VSCODE:=true}

# MySQL
# https://dev.mysql.com/downloads/repo/apt/
MYSQL_REPO=${MYSQL_REPO:=mysql-apt-config_0.8.28-1_all.deb}
MYSQL_USER=${MYSQL_USER:=mysql}
MYSQL_LOG=${MYSQL_LOG:=/var/log/mysql}

# Nginx
NGINX_LOG=${NGINX_LOG:=/var/log/nginx}
NGINX_CERT_PATH=${NGINX_CERT_PATH:=}
NGINX_DEFAULT=${NGINX_DEFAULT:=false}

# Apache/PHP
APACHE_USER=${APACHE_USER:=www-data}
APACHE_LOG=${APACHE_LOG:=/var/log/apache2}
APACHE_PORT=${APACHE_PORT:=8081}
PHP_VER=${PHP_VER:=7.4}

# Code-Server
# https://github.com/coder/code-server/releases
CODESERVER_VER=${CODESERVER_VER:=4.18.0}
CODESERVER_PASS=${CODESERVER_PASS:=password}
CODESERVER_PORT=${CODESERVER_PORT:=8082}
if [ -z "${CODESERVER_EXTS}" ]; then
    CODESERVER_EXTS=(
        # Apache Conf
        "mrmlnc.vscode-apache"
        # Auto Open Preview Panel
        "matt-rudge.auto-open-preview-panel"
        # Bash IDE
        "mads-hartmann.bash-ide-vscode"
        # Better Comments
        "aaron-bond.better-comments"
        # Better Shell Syntax
        "jeff-hykin.better-shellscript-syntax"
        # Code Spell Checker
        "streetsidesoftware.code-spell-checker"
        # Dendron Markdown Shortcuts
        "dendron.dendron-markdown-shortcuts"
        # Explicit Folding
        "zokugun.explicit-folding"
        # Git Graph
        "mhutchie.git-graph"
        # Git History
        "donjayamanne.githistory"
        # Inline SQL
        "qufiwefefwoyn.inline-sql-syntax"
        # markdownlint
        "DavidAnson.vscode-markdownlint"
        # php cs fixer
        "junstyle.php-cs-fixer"
        # Render line endings
        "medo64.render-crlf"
        # shell-format
        "foxundermoon.shell-format"
        # Sort lines
        "Tyriar.sort-lines"
    )
fi

#Others
if [ -z "${ALLOWED_PORTS}" ]; then
    ALLOWED_PORTS=()
fi
if [ -z "${CRON_JOBS}" ]; then
    CRON_JOBS=(
        "*/5 * * * * /bin/sh -c 'cd ${DOCPATH_ROOT} && /usr/bin/git fetch --all && /usr/bin/git pull origin master'"
        "*/5 * * * * /bin/sh -c 'cd ${DOCPATH_STATIC} && /usr/bin/git fetch --all && /usr/bin/git pull origin master'"
    )
fi
